/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * Modified by Minghua Shen, 2026.
 */
// v2 FAGGeneral backward combo, TND variant, headdim=192 softcap=true.
// Fixes the (headdim, softcap) pair at compile time and switches over
// causal x deterministic x dropout (8 FAGGeneral instantiations) so the 64
// variants of one (dtype, layout) family compile in 8 parallel TUs.
// Generated by autogen/generate_kernels.py - do not edit by hand.

#include "../fag_kernel_launch.hpp"

void fag_combo_bf16_tnd_headdim192_softcap1(const FagGeneralLaunchArgs &a) {
    auto fag_call = [=]() -> int {
        FAG_BOOL_SWITCH(a.is_causal, IsAttenMask, {
            FAG_BOOL_SWITCH(a.deterministic, IsDtm, {
                FAG_BOOL_SWITCH(a.has_dropout, IsDrop, {
                    FAG_KERNEL_LAUNCH(bfloat16_t, TND, Aligned192, IsAttenMask, IsDrop, IsDtm, true);
                });
            });
        });
        return 0;
    };
    at_npu::native::OpCommand::RunOpApiV2("ascendc_fag", fag_call);
}
