/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * Modified by Minghua Shen, 2026.
 */
#pragma once

// Generated by autogen/generate_kernels.py - do not edit by hand.
//
// Declarations of the 32 v2 FAGGeneral combo launchers (dtype x layout x
// headdim x softcap; each combo TU instantiates the 8 causal x
// deterministic x dropout FAGGeneral variants) plus the dispatcher macro
// used by fag_general_dispatch_impl.hpp. The macro `return`s out of the
// enclosing void dispatcher, so exactly one combo runs per dispatch.

#include "../fag_general_dispatch.hpp"

void fag_combo_fp16_bsnd_headdim64_softcap0(const FagGeneralLaunchArgs &a);
void fag_combo_fp16_bsnd_headdim64_softcap1(const FagGeneralLaunchArgs &a);
void fag_combo_fp16_bsnd_headdim128_softcap0(const FagGeneralLaunchArgs &a);
void fag_combo_fp16_bsnd_headdim128_softcap1(const FagGeneralLaunchArgs &a);
void fag_combo_fp16_bsnd_headdim192_softcap0(const FagGeneralLaunchArgs &a);
void fag_combo_fp16_bsnd_headdim192_softcap1(const FagGeneralLaunchArgs &a);
void fag_combo_fp16_bsnd_headdim256_softcap0(const FagGeneralLaunchArgs &a);
void fag_combo_fp16_bsnd_headdim256_softcap1(const FagGeneralLaunchArgs &a);
void fag_combo_fp16_tnd_headdim64_softcap0(const FagGeneralLaunchArgs &a);
void fag_combo_fp16_tnd_headdim64_softcap1(const FagGeneralLaunchArgs &a);
void fag_combo_fp16_tnd_headdim128_softcap0(const FagGeneralLaunchArgs &a);
void fag_combo_fp16_tnd_headdim128_softcap1(const FagGeneralLaunchArgs &a);
void fag_combo_fp16_tnd_headdim192_softcap0(const FagGeneralLaunchArgs &a);
void fag_combo_fp16_tnd_headdim192_softcap1(const FagGeneralLaunchArgs &a);
void fag_combo_fp16_tnd_headdim256_softcap0(const FagGeneralLaunchArgs &a);
void fag_combo_fp16_tnd_headdim256_softcap1(const FagGeneralLaunchArgs &a);
void fag_combo_bf16_bsnd_headdim64_softcap0(const FagGeneralLaunchArgs &a);
void fag_combo_bf16_bsnd_headdim64_softcap1(const FagGeneralLaunchArgs &a);
void fag_combo_bf16_bsnd_headdim128_softcap0(const FagGeneralLaunchArgs &a);
void fag_combo_bf16_bsnd_headdim128_softcap1(const FagGeneralLaunchArgs &a);
void fag_combo_bf16_bsnd_headdim192_softcap0(const FagGeneralLaunchArgs &a);
void fag_combo_bf16_bsnd_headdim192_softcap1(const FagGeneralLaunchArgs &a);
void fag_combo_bf16_bsnd_headdim256_softcap0(const FagGeneralLaunchArgs &a);
void fag_combo_bf16_bsnd_headdim256_softcap1(const FagGeneralLaunchArgs &a);
void fag_combo_bf16_tnd_headdim64_softcap0(const FagGeneralLaunchArgs &a);
void fag_combo_bf16_tnd_headdim64_softcap1(const FagGeneralLaunchArgs &a);
void fag_combo_bf16_tnd_headdim128_softcap0(const FagGeneralLaunchArgs &a);
void fag_combo_bf16_tnd_headdim128_softcap1(const FagGeneralLaunchArgs &a);
void fag_combo_bf16_tnd_headdim192_softcap0(const FagGeneralLaunchArgs &a);
void fag_combo_bf16_tnd_headdim192_softcap1(const FagGeneralLaunchArgs &a);
void fag_combo_bf16_tnd_headdim256_softcap0(const FagGeneralLaunchArgs &a);
void fag_combo_bf16_tnd_headdim256_softcap1(const FagGeneralLaunchArgs &a);

#define FAG_SELECT_COMBO_16(dt, ly)                                  \
    do {                                                              \
        if (a.is_softcap) {                                           \
            switch (a.qk_headdim_kernel) {                            \
                case 64:  fag_combo_##dt##_##ly##_headdim64_softcap1(a);  return; \
                case 128: fag_combo_##dt##_##ly##_headdim128_softcap1(a); return; \
                case 192: fag_combo_##dt##_##ly##_headdim192_softcap1(a); return; \
                case 256: fag_combo_##dt##_##ly##_headdim256_softcap1(a); return; \
                default: break;                                       \
            }                                                     \
        }                                                         \
        switch (a.qk_headdim_kernel) {                            \
            case 64:  fag_combo_##dt##_##ly##_headdim64_softcap0(a);  return; \
            case 128: fag_combo_##dt##_##ly##_headdim128_softcap0(a); return; \
            case 192: fag_combo_##dt##_##ly##_headdim192_softcap0(a); return; \
            case 256: fag_combo_##dt##_##ly##_headdim256_softcap0(a); return; \
            default: break;                                       \
        }                                                         \
    } while (0)
