/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * Modified by Minghua Shen, 2026.
 */
#pragma once

// Generated by autogen/generate_kernels.py - do not edit by hand.
//
// Declarations of the 32 v2 forward combo launchers (dtype x layout x
// softcap x return_softmax x dropout; each combo TU instantiates the 6
// paged x mask FAInfer variants) plus the dispatcher macro used by
// fwd_dispatch_impl.hpp. The macro `return`s out of the enclosing void
// dispatcher, so exactly one combo runs per dispatch.

#include "../fwd_dispatch.hpp"

void fwd_combo_fp16_bsnd_softcap0_retsoftmax0_dropout0(const FwdLaunchArgs &a);
void fwd_combo_fp16_bsnd_softcap0_retsoftmax0_dropout1(const FwdLaunchArgs &a);
void fwd_combo_fp16_bsnd_softcap0_retsoftmax1_dropout0(const FwdLaunchArgs &a);
void fwd_combo_fp16_bsnd_softcap0_retsoftmax1_dropout1(const FwdLaunchArgs &a);
void fwd_combo_fp16_bsnd_softcap1_retsoftmax0_dropout0(const FwdLaunchArgs &a);
void fwd_combo_fp16_bsnd_softcap1_retsoftmax0_dropout1(const FwdLaunchArgs &a);
void fwd_combo_fp16_bsnd_softcap1_retsoftmax1_dropout0(const FwdLaunchArgs &a);
void fwd_combo_fp16_bsnd_softcap1_retsoftmax1_dropout1(const FwdLaunchArgs &a);
void fwd_combo_fp16_tnd_softcap0_retsoftmax0_dropout0(const FwdLaunchArgs &a);
void fwd_combo_fp16_tnd_softcap0_retsoftmax0_dropout1(const FwdLaunchArgs &a);
void fwd_combo_fp16_tnd_softcap0_retsoftmax1_dropout0(const FwdLaunchArgs &a);
void fwd_combo_fp16_tnd_softcap0_retsoftmax1_dropout1(const FwdLaunchArgs &a);
void fwd_combo_fp16_tnd_softcap1_retsoftmax0_dropout0(const FwdLaunchArgs &a);
void fwd_combo_fp16_tnd_softcap1_retsoftmax0_dropout1(const FwdLaunchArgs &a);
void fwd_combo_fp16_tnd_softcap1_retsoftmax1_dropout0(const FwdLaunchArgs &a);
void fwd_combo_fp16_tnd_softcap1_retsoftmax1_dropout1(const FwdLaunchArgs &a);
void fwd_combo_bf16_bsnd_softcap0_retsoftmax0_dropout0(const FwdLaunchArgs &a);
void fwd_combo_bf16_bsnd_softcap0_retsoftmax0_dropout1(const FwdLaunchArgs &a);
void fwd_combo_bf16_bsnd_softcap0_retsoftmax1_dropout0(const FwdLaunchArgs &a);
void fwd_combo_bf16_bsnd_softcap0_retsoftmax1_dropout1(const FwdLaunchArgs &a);
void fwd_combo_bf16_bsnd_softcap1_retsoftmax0_dropout0(const FwdLaunchArgs &a);
void fwd_combo_bf16_bsnd_softcap1_retsoftmax0_dropout1(const FwdLaunchArgs &a);
void fwd_combo_bf16_bsnd_softcap1_retsoftmax1_dropout0(const FwdLaunchArgs &a);
void fwd_combo_bf16_bsnd_softcap1_retsoftmax1_dropout1(const FwdLaunchArgs &a);
void fwd_combo_bf16_tnd_softcap0_retsoftmax0_dropout0(const FwdLaunchArgs &a);
void fwd_combo_bf16_tnd_softcap0_retsoftmax0_dropout1(const FwdLaunchArgs &a);
void fwd_combo_bf16_tnd_softcap0_retsoftmax1_dropout0(const FwdLaunchArgs &a);
void fwd_combo_bf16_tnd_softcap0_retsoftmax1_dropout1(const FwdLaunchArgs &a);
void fwd_combo_bf16_tnd_softcap1_retsoftmax0_dropout0(const FwdLaunchArgs &a);
void fwd_combo_bf16_tnd_softcap1_retsoftmax0_dropout1(const FwdLaunchArgs &a);
void fwd_combo_bf16_tnd_softcap1_retsoftmax1_dropout0(const FwdLaunchArgs &a);
void fwd_combo_bf16_tnd_softcap1_retsoftmax1_dropout1(const FwdLaunchArgs &a);

#define FWD_SELECT_COMBO_8(dt, ly)                                                                          \
    do {                                                                                                      \
        if (!a.has_softcap && !a.return_softmax && !a.has_dropout) { fwd_combo_##dt##_##ly##_softcap0_retsoftmax0_dropout0(a); return; } \
        if (!a.has_softcap && !a.return_softmax &&  a.has_dropout) { fwd_combo_##dt##_##ly##_softcap0_retsoftmax0_dropout1(a); return; } \
        if (!a.has_softcap &&  a.return_softmax && !a.has_dropout) { fwd_combo_##dt##_##ly##_softcap0_retsoftmax1_dropout0(a); return; } \
        if (!a.has_softcap &&  a.return_softmax &&  a.has_dropout) { fwd_combo_##dt##_##ly##_softcap0_retsoftmax1_dropout1(a); return; } \
        if ( a.has_softcap && !a.return_softmax && !a.has_dropout) { fwd_combo_##dt##_##ly##_softcap1_retsoftmax0_dropout0(a); return; } \
        if ( a.has_softcap && !a.return_softmax &&  a.has_dropout) { fwd_combo_##dt##_##ly##_softcap1_retsoftmax0_dropout1(a); return; } \
        if ( a.has_softcap &&  a.return_softmax && !a.has_dropout) { fwd_combo_##dt##_##ly##_softcap1_retsoftmax1_dropout0(a); return; } \
        fwd_combo_##dt##_##ly##_softcap1_retsoftmax1_dropout1(a);                                                \
    } while (0)
