/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * Modified by Minghua Shen, 2026.
 */
// v2 forward FAInfer combo, TND variant, softcap=false return_softmax=false dropout=false.
// Fixes the (softcap, return_softmax, dropout) triple at compile time and
// switches over paged x mask (6 FAInfer instantiations) so the 48 variants
// of one (dtype, layout) family compile in 8 parallel TUs. Generated by
// autogen/generate_kernels.py - do not edit by hand.

#include "../fwd_kernel_launch.hpp"

void fwd_combo_bf16_tnd_softcap0_retsoftmax0_dropout0(const FwdLaunchArgs &a) {
    FWD_BOOL_SWITCH(a.paged_KV, IsPaged, {
        FWD_MASK_SWITCH(a.is_local, a.is_causal, MaskType, {
            FWD_KERNEL_LAUNCH(bfloat16_t, IsPaged, MaskType, FaiKenel::inputLayout::TND, false, false, false);
        });
    });
}
